In [1]:
# mimporting libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split


In [2]:
#import data set and preprocessing data
import sklearn.datasets as da
data = da.load_breast_cancer()

label=data.feature_names
x=data.data
y=data.target

X=pd.DataFrame(x)
Y=pd.DataFrame(y)

X.columns=label
Y.columns=['diabetes']

In [3]:
#splitting into test and train set

train_X , test_X , train_Y , test_Y =train_test_split(X,Y,test_size=0.20,random_state=0)

#feature sclaing
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
train_X=sc_x.fit_transform(train_X)
test_X=sc_x.fit_transform(test_X)

In [9]:

#building neural network model /relu activation function

neural=MLPClassifier(hidden_layer_sizes=(50,50,) , activation="relu" , alpha=0.001 , learning_rate="constant" )
neural.fit(train_X ,train_Y)
neural.score(train_X ,train_Y)

#evalutaing test result
pred=neural.predict(test_X)

from sklearn.metrics import accuracy_score ,confusion_matrix
cm=confusion_matrix(test_Y,pred)
print('the confusion matrix is ')
print(cm)
accuracy_score(test_Y,pred)*100

C:\Users\lab102-20\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


the confusion matrix is 
[[46  1]
 [ 1 66]]


C:\Users\lab102-20\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


98.24561403508771

In [10]:
#building neural network model /tanh activation function

neural=MLPClassifier(hidden_layer_sizes=(50,50,) , activation="tanh" , alpha=0.001 , learning_rate="constant" )
neural.fit(train_X ,train_Y)
neural.score(train_X ,train_Y)

#evalutaing test result
pred=neural.predict(test_X)

from sklearn.metrics import accuracy_score ,confusion_matrix
cm=confusion_matrix(test_Y,pred)
print('the confusion matrix is ')
print(cm)
accuracy_score(test_Y,pred)*100

C:\Users\lab102-20\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


the confusion matrix is 
[[45  2]
 [ 0 67]]


C:\Users\lab102-20\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


98.24561403508771

In [11]:
#building neural network model /logistic activation function

neural=MLPClassifier(hidden_layer_sizes=(50,50,) , activation="logistic" , alpha=0.001 , learning_rate="constant" )
neural.fit(train_X ,train_Y)
neural.score(train_X ,train_Y)

#evalutaing test result
pred=neural.predict(test_X)

from sklearn.metrics import accuracy_score ,confusion_matrix
cm=confusion_matrix(test_Y,pred)
print('the confusion matrix is ')
print(cm)
accuracy_score(test_Y,pred)*100

C:\Users\lab102-20\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


the confusion matrix is 
[[45  2]
 [ 1 66]]


C:\Users\lab102-20\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


97.36842105263158

In [12]:
#building neural network model /identity activation function

neural=MLPClassifier(hidden_layer_sizes=(50,50,) , activation="identity" , alpha=0.001 , learning_rate="constant" )
neural.fit(train_X ,train_Y)
neural.score(train_X ,train_Y)

#evalutaing test result
pred=neural.predict(test_X)

from sklearn.metrics import accuracy_score ,confusion_matrix
cm=confusion_matrix(test_Y,pred)
print('the confusion matrix is ')
print(cm)
accuracy_score(test_Y,pred)*100

C:\Users\lab102-20\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


the confusion matrix is 
[[45  2]
 [ 3 64]]


95.6140350877193